name: CI with SonarQube and Conditional Deploy
   
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build with Maven
        run: mvn clean install -DskipTests   
      
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      
      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v6
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Run SonarCloud scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
            -Dsonar.organization=grimorio11 \
            -Dsonar.projectKey=grimorio11_prueba \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=.

      - name: Verificar archivos compilados
        run: find . -name "report-task.txt" # target/classes

      # - name: SonarQube Quality Gate check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  check-quality-gate:
    name: Check SonarQube Quality Gate
    runs-on: ubuntu-latest
    needs: build-and-analyze
    steps:
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: ./target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: check-quality-gate
    if: success()  # Solo se ejecuta si el job anterior pasó
    steps:
      - name: Deploy to production
        run: echo "Desplegando aplicación..."
