name: CI with SonarCloud and Conditional Deploy

on:
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para análisis de historial por SonarCloud

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarCloud scan
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar\
            -Dsonar.organization=grimorio11 \
            -Dsonar.projectKey=grimorio11_prueba \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes

      - name: Busca archivo
        run: find . -name "report-task.txt"

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: ./target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-and-analyze
    if: success()
    steps:
      - name: Deploy to production
        run: echo "Desplegando aplicación..."
